# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudInspector' do
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CloudInspector
   # Use the following line to use App Center Analytics and Crashes.
 

 # Use the following lines if you want to specify which service you want to use.
 pod 'AppCenter/Analytics', '~> 1.13.0'
 
  platform :ios, '9.0'
end

