# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Papsi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Papsi


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end
