import {DocumentDirectoryPath} from 'react-native-fs';

export const CREATE_VISIT_REQUEST = 'CREATE_VISIT_REQUEST';
export const CREATE_VISIT_RESPONSE = 'CREATE_VISIT_RESPONSE';
export const CREATE_VISIT_ERROR = 'CREATE_VISIT_ERROR';
export const GET_VISIT_REQUEST = 'GET_VISIT_REQUEST';
export const GET_VISIT_RESPONSE = 'GET_VISIT_RESPONSE';
export const GET_VISIT_ERROR = 'GET_VISIT_ERROR';
export const SET_VISIT_OFFLINE = 'SET_VISIT_OFFLINE';
export const SET_LAST_CREATED_ID = 'SET_LAST_CREATED_ID';
export const REFRESH_VISIT_REQUEST = 'REFRESH_VISIT_REQUEST';
export const REFRESH_VISIT_RESPONSE = 'REFRESH_VISIT_RESPONSE';
export const REFRESH_VISIT_ERROR = 'REFRESH_VISIT_ERROR';
export const SYNC_VISIT_REQUEST = 'SYNC_VISIT_REQUEST';
export const SYNC_VISIT_RESPONSE = 'SYNC_VISIT_RESPONSE';
export const SYNC_VISIT_ERROR = 'SYNC_VISIT_ERROR';
export const SET_SYNC_VISIT = 'SET_SYNC_VISIT';
export const SET_STORED_VISITS = 'SET_STORED_VISITS';
export const DELETE_OFFLINE_VISIT = 'DELETE_OFFLINE_VISIT';
export const SET_TASK_NAMES = 'SET_TASK_NAMES';
export const ADD_TASK_NAME = 'ADD_TASK_NAME';

export const SYNC_VISIT_START = 'SYNC_VISIT_START';
export const SYNC_VISIT_END = 'SYNC_VISIT_END';

export const SET_APP_DATA = 'SET_APP_DATA';
export const UPDATE_RATIO_EXCEPTIONS_REQUEST = 'UPDATE_RATIO_EXCEPTIONS_REQUEST';
export const SET_RATIO_EXCEPTIONS = 'SET_RATIO_EXCEPTIONS';
export const SET_FORCE_SYNC = 'SET_FORCE_SYNC';

export const GET_TASKS_REQUEST_START = 'GET_TASKS_REQUEST_START';
export const GET_TASKS_REQUEST_END = 'GET_TASKS_REQUEST_END';
export const SET_TASKS = 'SET_TASKS';

export const SHOPS_REQUEST = 'SHOPS_REQUEST';
export const SHOPS_REQUEST_END = 'SHOPS_REQUEST_END';
export const SHOPS_RESPONSE = 'SHOPS_RESPONSE';
export const SHOPS_ERROR = 'SHOPS_ERROR';
export const SHOPS_REQUEST_NEXT = 'SHOPS_REQUEST_NEXT';

export const SHOP_REQUEST = "SHOP_REQUEST";
export const SHOP_RESPONSE = "SHOP_RESPONSE";


export const DEL_FAVORITE = 'DEL_FAVORITE';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_FAVORITE = 'SET_FAVORITE';
export const SET_FAVORITE_FETCH = 'SET_FAVORITE_FETCH';

export const SET_GEO_STATUS = 'SET_GEO_STATUS';
export const SET_GEO_FETCH = 'SET_GEO_FETCH';
export const SET_GEO_DATA = 'SET_GEO_DATA';
export const SET_GEO_ERROR = 'SET_GEO_ERROR';

export const SELECT_NEAREST = "SELECT_NEAREST";
export const SELECT_FAVORITES = "SELECT_FAVORITES";

export const SET_CAMERA_TYPE = "SET_CAMERA_TYPE";

export const GET_VISIT_DETAILS_REQUEST = 'GET_VISIT_DETAILS_REQUEST';
export const GET_VISIT_DETAILS_RESPONSE = 'GET_VISIT_DETAILS_RESPONSE';
export const GET_VISIT_DETAILS_ERROR = 'GET_VISIT_DETAILS_ERROR';
export const CLEAR_VISIT_DETAILS = 'CLEAR_VISIT_DETAILS';
export const CHANGE_VISIT_ID_REQUEST = 'CHANGE_VISIT_ID_REQUEST';
export const CHANGE_VISIT_ID_RESPONSE = 'CHANGE_VISIT_ID_RESPONSE';
export const CHANGE_VISIT_ROUTE_RESPONSE = 'CHANGE_VISIT_ROUTE_RESPONSE';
export const CHANGE_VISIT_ROUTE_REQUEST = 'CHANGE_VISIT_ROUTE_REQUEST';

export const DEBUG_CLEAR_SYNC_STORE = 'DEBUG_CLEAR_SYNC_STORE';
export const DEBUG_CLEAR_OFFLINE_STORE = 'DEBUG_CLEAR_OFFLINE_STORE';
export const DEBUG_CLEAR_PHOTOS_STORE = 'DEBUG_CLEAR_PHOTOS_STORE';

export const SEND_FEEDBACK_REQUEST = "SEND_FEEDBACK_REQUEST";
export const SEND_FEEDBACK_TIMEOUT = "SEND_FEEDBACK_TIMEOUT";
export const SEND_FEEDBACK_RESPONSE = "SEND_FEEDBACK_RESPONSE";
export const FEEDBACK_CLEAR_ERROR = "FEEDBACK_CLEAR_ERROR";

export const AGENT_FETCH = "AGENT_FETCH";
export const SET_AUTH_ID = "SET_AUTH_ID";
export const SET_PIN = "SET_PIN";
export const SET_PINS = "SET_PINS";
export const FETCH_PIN = "FETCH_PIN";
export const SET_INSTANCE = "SET_INSTANCE";
export const FETCH_PIN_ERROR = "FETCH_PIN_ERROR";
export const FETCH_PIN_RESPONSE = "FETCH_PIN_RESPONSE";
export const SYNC_PINS_START = "SYNC_PINS_START";
export const SYNC_PINS_START_FIRST = "SYNC_PINS_START_FIRST";
export const SYNC_PINS_END = "SYNC_PINS_END";
export const SYNC_PINS_REQUEST = "SYNC_PINS_REQUEST";
export const SYNC_PINS_RESPONSE = "SYNC_PINS_RESPONSE";

export const SHOW_TOAST = 'SHOW_TOAST';
export const SET_SYNC_TIME = 'SET_SYNC_TIME';
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';

export const SET_STATISTICS = 'SET_STATISTICS';

export const SET_PROFILE_SURMANE = 'SET_PROFILE_SURMANE';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_PROFILE_NAME = 'SET_PROFILE_NAME';
export const SET_PROFILE_PATRONYMIC = 'SET_PROFILE_PATRONYMIC';
export const SET_PROFILE_PATH_NUMBER = 'SET_PROFILE_PATH_NUMBER';
export const SET_PROFILE_CONTACT_NUMBER = 'SET_PROFILE_CONTACT_NUMBER';
export const SET_PROFILE_FIELD_VALUE = 'SET_PROFILE_FIELD_VALUE';

export const photoDir = DocumentDirectoryPath + "/photos/";