export const CREATE_VISIT_REQUEST = 'CREATE_VISIT_REQUEST';
export const CREATE_VISIT_RESPONSE = 'CREATE_VISIT_RESPONSE';
export const CREATE_VISIT_ERROR = 'CREATE_VISIT_ERROR';
export const GET_VISIT_REQUEST = 'GET_VISIT_REQUEST';
export const GET_VISIT_RESPONSE = 'GET_VISIT_RESPONSE';
export const GET_VISIT_ERROR = 'GET_VISIT_ERROR';
export const SET_VISIT_OFFLINE = 'SET_VISIT_OFFLINE';
export const REFRESH_VISIT_REQUEST = 'REFRESH_VISIT_REQUEST';
export const REFRESH_VISIT_RESPONSE = 'REFRESH_VISIT_RESPONSE';
export const REFRESH_VISIT_ERROR = 'REFRESH_VISIT_ERROR';
export const SYNC_VISIT_REQUEST = 'SYNC_VISIT_REQUEST';
export const SYNC_VISIT_RESPONSE = 'SYNC_VISIT_RESPONSE';
export const SET_SYNC_VISIT = 'SET_SYNC_VISIT';

export const SYNC_VISIT_START = 'SYNC_VISIT_START';
export const SYNC_VISIT_END = 'SYNC_VISIT_END';

export const SET_APP_DATA = 'SET_APP_DATA';

export const GET_VISIT_DETAILS_REQUEST = 'GET_VISIT_DETAILS_REQUEST';
export const GET_VISIT_DETAILS_RESPONSE = 'GET_VISIT_DETAILS_RESPONSE';
export const GET_VISIT_DETAILS_ERROR = 'GET_VISIT_DETAILS_ERROR';
export const CLEAR_VISIT_DETAILS = 'CLEAR_VISIT_DETAILS';

export const SET_AUTH_ID = "SET_AUTH_ID"

export const SHOW_TOAST = 'SHOW_TOAST'
export const SET_SYNC_TIME = 'SET_SYNC_TIME'
export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS'

export const SET_PROFILE_SURMANE = 'SET_PROFILE_SURMANE';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const SET_PROFILE_NAME = 'SET_PROFILE_NAME';
export const SET_PROFILE_PATRONYMIC = 'SET_PROFILE_PATRONYMIC';
export const SET_PROFILE_PATH_NUMBER = 'SET_PROFILE_PATH_NUMBER';
export const SET_PROFILE_CONTACT_NUMBER = 'SET_PROFILE_CONTACT_NUMBER';